### ISSUE TITLE
SourceFormats endpoint - Create

### ISSUE THREAD

**Issue by Andras-Csanyi** [EncyclopediaGalactica/EG#4]
# Summary
SourceFormat data structure defines a tree structure which reflects on a document format like `HTML`, `XML` or `TXT`. The SourceFormat is the spine of the whole and eventually additional information holder elements will be attached to it.

Overall, the Data Curator role in the system has to be able to manage this data structure via REST endpoint.

# Task
- add create capabilities to SourceFormat endpoint
- it accepts `SourceFormatDto` object
- it returns `SourceFormatDto` object
- it returns `201` when the new object is created and returns with the new one too
- it returns `404` when endpoint is not found
- it returns `400` when validation fails with `Invalid input` error message
- it returns `500` when internal error happens without any details
- it returns `401` when user is not authenticated to use this endpoint with `User is not authenticated` error message
- it returns `403` when user is authenticated but not authorized with `User is not authorized to use this endpoint` message
- it returns `JSON` format

# Definition of Done
- [ ] it accepts `SourceFormatDto` object
- [ ] it returns `SourceFormatDto` object
- [ ] it returns `201` when the new object is created and returns with the new one too
- [ ] it returns `404` when endpoint is not found
- [ ] it returns `400` when validation fails with `Invalid input` error message --> #5 
- [ ] it returns `500` when internal error happens without any details
- [ ] it returns `401` when user is not authenticated to use this endpoint with `User is not authenticated` error message
- [ ] it returns `403` when user is authenticated but not authorized with `User is not authorized to use this endpoint` message
- [ ] it returns `JSON` format
- [ ] the service has E2E tests
