### ISSUE TITLE
SourceFormats endpoint - GetAll

### ISSUE THREAD

**Issue by Andras-Csanyi** [EncyclopediaGalactica/EG#8]
# Summary
We need functionality which lists all of the SourceFormat entities in the system

# Task
- add `getAll` capabilities to SourceFormat endpoint
- it returns `200` when the request processed successfully
- it returns `404` when endpoint is not found
- it returns `500` when internal error happens without any details
- it returns `415` when user posts an unsupported media type content
- it returns `JSON` format

# Definition of Done
- [x] it returns `200` when the request processed successfully
- [x] it returns `404` when endpoint is not found
- [x] it returns `500` when internal error happens without any details
- [x] it returns `415` when user posts an unsupported media type content
- [x] it returns `JSON` format
- [x] returns list of entities
- [x] when the result is empty returns an empty list
- [x] the service has E2E tests

#9
